/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ActivatedNotes } from "./components/tiny-tonnetz/tiny-tonnetz";
import { ActivatedNotes as ActivatedNotes1 } from "./components/tiny-tonnetz/tiny-tonnetz";
export { ActivatedNotes } from "./components/tiny-tonnetz/tiny-tonnetz";
export { ActivatedNotes as ActivatedNotes1 } from "./components/tiny-tonnetz/tiny-tonnetz";
export namespace Components {
    interface TinyTonnetz {
        "activatedNotes"?: ActivatedNotes;
        "marginUnitCellCount": number;
        "scale": number;
    }
    interface TinyTonnetzCell {
        "activatedNotes"?: ActivatedNotes1;
        "height": number;
        "primary": boolean;
        "semiToneCode": number;
        "width": number;
    }
}
declare global {
    interface HTMLTinyTonnetzElement extends Components.TinyTonnetz, HTMLStencilElement {
    }
    var HTMLTinyTonnetzElement: {
        prototype: HTMLTinyTonnetzElement;
        new (): HTMLTinyTonnetzElement;
    };
    interface HTMLTinyTonnetzCellElement extends Components.TinyTonnetzCell, HTMLStencilElement {
    }
    var HTMLTinyTonnetzCellElement: {
        prototype: HTMLTinyTonnetzCellElement;
        new (): HTMLTinyTonnetzCellElement;
    };
    interface HTMLElementTagNameMap {
        "tiny-tonnetz": HTMLTinyTonnetzElement;
        "tiny-tonnetz-cell": HTMLTinyTonnetzCellElement;
    }
}
declare namespace LocalJSX {
    interface TinyTonnetz {
        "activatedNotes"?: ActivatedNotes;
        "marginUnitCellCount"?: number;
        "scale"?: number;
    }
    interface TinyTonnetzCell {
        "activatedNotes"?: ActivatedNotes1;
        "height"?: number;
        "primary"?: boolean;
        "semiToneCode"?: number;
        "width"?: number;
    }
    interface IntrinsicElements {
        "tiny-tonnetz": TinyTonnetz;
        "tiny-tonnetz-cell": TinyTonnetzCell;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tiny-tonnetz": LocalJSX.TinyTonnetz & JSXBase.HTMLAttributes<HTMLTinyTonnetzElement>;
            "tiny-tonnetz-cell": LocalJSX.TinyTonnetzCell & JSXBase.HTMLAttributes<HTMLTinyTonnetzCellElement>;
        }
    }
}
