/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TinyTonnetz {
        "marginUnitCellCount": number;
        "scale": number;
    }
}
declare global {
    interface HTMLTinyTonnetzElement extends Components.TinyTonnetz, HTMLStencilElement {
    }
    var HTMLTinyTonnetzElement: {
        prototype: HTMLTinyTonnetzElement;
        new (): HTMLTinyTonnetzElement;
    };
    interface HTMLElementTagNameMap {
        "tiny-tonnetz": HTMLTinyTonnetzElement;
    }
}
declare namespace LocalJSX {
    interface TinyTonnetz {
        "marginUnitCellCount"?: number;
        "scale"?: number;
    }
    interface IntrinsicElements {
        "tiny-tonnetz": TinyTonnetz;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tiny-tonnetz": LocalJSX.TinyTonnetz & JSXBase.HTMLAttributes<HTMLTinyTonnetzElement>;
        }
    }
}
